const CONFIG_ID = '$';
const HOOK_START = '$';
const STATE = `${HOOK_START}state`;
const TEMPLATE_CONDITIONAL_EXPRESSION = `${CONFIG_ID}.ce`
const GET_VALUE = 'v';
const CREATE_REACTIVE_VALUE = 'r';
const HYDRATE = 'h';
const CONDITIONAL = 'if';
const LIST = 'for'

export {
  CONDITIONAL,
  LIST,
  CONFIG_ID,
  HOOK_START,
  STATE,
  GET_VALUE,
  HYDRATE,
  TEMPLATE_CONDITIONAL_EXPRESSION,
  CREATE_REACTIVE_VALUE
}